/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telaprincipal;

/**
 *
 * @author nizio
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        ButtonAmigos = new javax.swing.JMenu();
        ButtonDeletarAmigos = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        ButtonFerramentas = new javax.swing.JMenu();
        ButtonCadastrarEditarFerramentas = new javax.swing.JMenu();
        ButtonDeletarFerramentas = new javax.swing.JMenu();
        buttonRegistrodeEmpréstimos = new javax.swing.JMenu();
        ButtonRegistrodeEmpréstimos1 = new javax.swing.JMenu();
        ButtonDeletarEmpréstimos = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ButtonAmigos.setText("Amigos");

        ButtonDeletarAmigos.setText("Cadastrar/Editar Amigos");
        ButtonAmigos.add(ButtonDeletarAmigos);

        jMenu4.setText("Deletar Amigos ");
        ButtonAmigos.add(jMenu4);

        jMenuBar1.add(ButtonAmigos);

        ButtonFerramentas.setText("Ferramentas");

        ButtonCadastrarEditarFerramentas.setText("Cadastrar/Editar Ferramentas");
        ButtonFerramentas.add(ButtonCadastrarEditarFerramentas);

        ButtonDeletarFerramentas.setText("Deletar Ferramentas");
        ButtonFerramentas.add(ButtonDeletarFerramentas);

        jMenuBar1.add(ButtonFerramentas);

        buttonRegistrodeEmpréstimos.setText("Registro de Empréstimos");

        ButtonRegistrodeEmpréstimos1.setText("Registro de Empréstimos");
        buttonRegistrodeEmpréstimos.add(ButtonRegistrodeEmpréstimos1);

        ButtonDeletarEmpréstimos.setText("Deletar Empréstimos");
        buttonRegistrodeEmpréstimos.add(ButtonDeletarEmpréstimos);

        jMenuBar1.add(buttonRegistrodeEmpréstimos);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 722, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 407, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu ButtonAmigos;
    private javax.swing.JMenu ButtonCadastrarEditarFerramentas;
    private javax.swing.JMenu ButtonDeletarAmigos;
    private javax.swing.JMenu ButtonDeletarEmpréstimos;
    private javax.swing.JMenu ButtonDeletarFerramentas;
    private javax.swing.JMenu ButtonFerramentas;
    private javax.swing.JMenu ButtonRegistrodeEmpréstimos1;
    private javax.swing.JMenu buttonRegistrodeEmpréstimos;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
